export const NEW_CLIENTS = [
  { name: "Barbearia Império", contactName: "Diego Cardozo", monthlyValue: 2200, status: "ACTIVE", months: 9, city: "Fortaleza - CE" },
  { name: "Imobiliária Raízes", contactName: "Fernanda Cavalcante", monthlyValue: 9500, status: "ACTIVE", months: 16, city: "Recife - PE" },
  { name: "Contábil Prisma Assessoria", contactName: "Marcos Vinícius Teixeira", monthlyValue: 3200, status: "ACTIVE", months: 7, city: "Salvador - BA" },
  { name: "Cão Cidadão Adestramento", contactName: "Juliana Marques", monthlyValue: 1800, status: "ACTIVE", months: 5, city: "Vitória - ES" },
  { name: "Tinta Negra Estúdio", contactName: "Rafael Cordeiro", monthlyValue: 2600, status: "ACTIVE", months: 11, city: "Manaus - AM" },
  { name: "Harmonia Escola de Música", contactName: "Cecília Braga", monthlyValue: 2900, status: "ACTIVE", months: 6, city: "Natal - RN" },
  { name: "Clínica Veterinária Patas & Cia", contactName: "Dra. Luíza Nogueira", monthlyValue: 6800, status: "ACTIVE", months: 13, city: "Uberlândia - MG" },
  { name: "TechPoint Eletrônicos", contactName: "Gustavo Andrade", monthlyValue: 7200, status: "ACTIVE", months: 4, city: "Joinville - SC" },
  { name: "Rota Livre Viagens", contactName: "Camila Duarte Reis", monthlyValue: 5800, status: "ACTIVE", months: 8, city: "Belém - PA" },
  { name: "Joalheria Estrela do Sul", contactName: "Isabela Franco", monthlyValue: 11000, status: "ACTIVE", months: 17, city: "Curitiba - PR" },
  { name: "Flor & Cia Floricultura", contactName: "Beatriz Sampaio", monthlyValue: 1600, status: "PAUSED", months: 3, city: "Campinas - SP" },
  { name: "Marcenaria Raiz Forte", contactName: "Anderson Vieira", monthlyValue: 4200, status: "ACTIVE", months: 10, city: "Londrina - PR" },
  { name: "Expresso 24h Conveniência", contactName: "Wellington Souza", monthlyValue: 3800, status: "CHURNED", months: 14, city: "Sorocaba - SP" },
] as const;

export const NEW_OPPORTUNITIES = [
  { name: "Sorveteria Gelato Puro", contact: "Camila Vasconcelos", stage: "Novo Lead", value: 2600, source: "Instagram", days: 18 },
  { name: "Estúdio Fit Box", contact: "Rodrigo Chaves", stage: "Novo Lead", value: 3400, source: "Google", days: 22 },
  { name: "Livraria Página Viva", contact: "Helena Marques", stage: "Novo Lead", value: 2100, source: "Indicação", days: 12 },
  { name: "Doceria da Vovó", contact: "Sônia Aparecida", stage: "Novo Lead", value: 1900, source: "Site", days: 27 },
  { name: "Clínica de Estética Renove", contact: "Dra. Patrícia Lima", stage: "Novo Lead", value: 5400, source: "LinkedIn", days: 9 },
  { name: "Auto Elétrica Potência", contact: "Marcelo Rezende", stage: "Novo Lead", value: 2800, source: "Indicação", days: 31 },
  { name: "Recanto Zen Massoterapia", contact: "Ana Beatriz Costa", stage: "Contato Feito", value: 3300, source: "Instagram", days: 14 },
  { name: "Mercadinho Vila Nova", contact: "José Roberto Lins", stage: "Contato Feito", value: 2400, source: "Site", days: 8 },
  { name: "Colégio Novo Horizonte", contact: "Direção Acadêmica", stage: "Contato Feito", value: 9800, source: "Indicação", days: 16 },
  { name: "Estética Automotiva Brilho Total", contact: "Igor Fagundes", stage: "Contato Feito", value: 3600, source: "Google", days: 11 },
  { name: "Clínica Odontológica Sorrir Mais", contact: "Dr. Vitor Hugo Amaral", stage: "Proposta Enviada", value: 7200, source: "Site", days: 6 },
  { name: "Pizzaria Forno & Arte", contact: "Guilherme Peixoto", stage: "Proposta Enviada", value: 4100, source: "Indicação", days: 5 },
  { name: "Studio de Dança Movimento", contact: "Larissa Bittencourt", stage: "Proposta Enviada", value: 3000, source: "Instagram", days: 7 },
  { name: "Rede de Farmácias Vitalle", contact: "Eduardo Campos", stage: "Negociação", value: 10500, source: "LinkedIn", days: 4 },
  { name: "Transportes Rápido Norte", contact: "Vanessa Oliveira Reis", stage: "Negociação", value: 6900, source: "Indicação", days: 6 },
  { name: "Buffet Momentos Especiais", contact: "Cristina Alves Ribeiro", stage: "Ganho", value: 5200, source: "Indicação", days: -6 },
] as const;
