export const WHATSAPP_CONVERSATIONS: { client: string; phoneSuffix: string; messages: { direction: "INBOUND" | "OUTBOUND"; text: string; hoursAgo: number }[] }[] = [
  {
    client: "Loja Aurora",
    phoneSuffix: "999990001",
    messages: [
      { direction: "INBOUND", text: "Oi! Vi as artes da campanha de inverno, ficaram lindas 😍", hoursAgo: 72 },
      { direction: "OUTBOUND", text: "Que bom que gostou, Marina! Posso agendar a publicação pra quinta então?", hoursAgo: 70 },
      { direction: "INBOUND", text: "Pode sim, só troca a cor de fundo do carrossel 3 pra bege, não combinou com a vitrine", hoursAgo: 69 },
      { direction: "OUTBOUND", text: "Combinado, já ajusto e te mando de novo até amanhã de manhã", hoursAgo: 68 },
      { direction: "INBOUND", text: "Bom dia! Chegou a versão nova?", hoursAgo: 20 },
      { direction: "OUTBOUND", text: "Chegou sim, olha só, ficou bem mais alinhado com a identidade", hoursAgo: 18 },
      { direction: "INBOUND", text: "Perfeita, pode publicar! Aprovado 👏", hoursAgo: 16 },
      { direction: "OUTBOUND", text: "Show, já entrou na fila de agendamento pra amanhã às 10h", hoursAgo: 14 },
    ],
  },
  {
    client: "Pele Bonita Cosméticos",
    phoneSuffix: "999990002",
    messages: [
      { direction: "INBOUND", text: "Fala, tudo bem? Vi que o investimento em anúncio subiu esse mês, mas as vendas não acompanharam na mesma proporção", hoursAgo: 96 },
      { direction: "OUTBOUND", text: "Oi Rodrigo! Vamos olhar com calma, pode ser sazonalidade ou algum criativo saturando. Te mando o relatório até amanhã", hoursAgo: 94 },
      { direction: "INBOUND", text: "Beleza, fico no aguardo", hoursAgo: 93 },
      { direction: "OUTBOUND", text: "Rodrigo, terminei a análise. O CPA subiu porque o público principal já viu o anúncio muitas vezes, vamos trocar os criativos", hoursAgo: 24 },
      { direction: "INBOUND", text: "Faz sentido. Quando isso entra no ar?", hoursAgo: 22 },
      { direction: "OUTBOUND", text: "Já deixei 3 criativos novos pra aprovação, te mando agora", hoursAgo: 20 },
      { direction: "INBOUND", text: "Vi aqui, gostei bastante. Pode subir", hoursAgo: 12 },
      { direction: "OUTBOUND", text: "Perfeito, subindo agora e acompanho de perto essa semana", hoursAgo: 10 },
    ],
  },
  {
    client: "Sabor Caseiro Restaurante",
    phoneSuffix: "999990003",
    messages: [
      { direction: "INBOUND", text: "Oi, tudo bem? Queria marcar uma reunião pra fechar o planejamento do próximo trimestre", hoursAgo: 50 },
      { direction: "OUTBOUND", text: "Oi Helena! Claro, essa semana ou semana que vem fica melhor pra você?", hoursAgo: 49 },
      { direction: "INBOUND", text: "Semana que vem, terça de manhã se possível", hoursAgo: 48 },
      { direction: "OUTBOUND", text: "Terça 10h funciona aqui, te mando o convite", hoursAgo: 47 },
      { direction: "INBOUND", text: "Recebi o convite, confirmado! Vou levar o cardápio novo pra gente pensar juntos no conteúdo", hoursAgo: 18 },
      { direction: "OUTBOUND", text: "Ótimo, vai ajudar bastante. Até terça!", hoursAgo: 16 },
    ],
  },
  {
    client: "TechFlow Soluções",
    phoneSuffix: "999990004",
    messages: [
      { direction: "INBOUND", text: "Pessoal, o material do lançamento ficou excelente, parabéns pelo trabalho", hoursAgo: 60 },
      { direction: "OUTBOUND", text: "Que alegria ouvir isso, Diego! O time se dedicou bastante nesse projeto", hoursAgo: 58 },
      { direction: "INBOUND", text: "Deu pra perceber, o vídeo institucional ficou show. Já estamos usando na reunião com investidores", hoursAgo: 57 },
      { direction: "OUTBOUND", text: "Fico muito feliz em saber! Qualquer ajuste que precisar é só chamar", hoursAgo: 56 },
      { direction: "INBOUND", text: "Vamos precisar de uma versão mais curta pra Stories, dá pra fazer?", hoursAgo: 15 },
      { direction: "OUTBOUND", text: "Dá sim, já coloco na fila e entrego até sexta", hoursAgo: 13 },
    ],
  },
  {
    client: "Vida Fitness Academia",
    phoneSuffix: "999990005",
    messages: [
      { direction: "INBOUND", text: "Oi! Olhei os posts da campanha de matrícula, ficaram bons mas o preço tá difícil de ler no fundo escuro", hoursAgo: 40 },
      { direction: "OUTBOUND", text: "Verdade, vou aumentar o contraste. Prefere fundo mais claro ou só destacar o texto?", hoursAgo: 38 },
      { direction: "INBOUND", text: "Acho que só destacar o texto já resolve, não quero perder a identidade visual", hoursAgo: 37 },
      { direction: "OUTBOUND", text: "Combinado, ajusto e mando ainda hoje", hoursAgo: 36 },
      { direction: "INBOUND", text: "Ficou ótimo agora, dá pra ler de longe. Pode publicar", hoursAgo: 19 },
      { direction: "OUTBOUND", text: "Publicando! Vou deixar impulsionado pro público de 5km ao redor da unidade", hoursAgo: 17 },
      { direction: "INBOUND", text: "Perfeito, obrigada pela agilidade", hoursAgo: 8 },
    ],
  },
  {
    client: "Doce Encanto Confeitaria",
    phoneSuffix: "999990006",
    messages: [
      { direction: "INBOUND", text: "Oi, bom dia! A fatura desse mês veio com um valor diferente do combinado, pode verificar?", hoursAgo: 30 },
      { direction: "OUTBOUND", text: "Bom dia Larissa! Vou checar agora com o financeiro e já te retorno", hoursAgo: 28 },
      { direction: "INBOUND", text: "Show, obrigada", hoursAgo: 27 },
      { direction: "OUTBOUND", text: "Larissa, identificamos: teve o serviço extra de fotos do Dia das Mães que entrou na fatura. Vou te mandar o detalhamento", hoursAgo: 25 },
      { direction: "INBOUND", text: "Ahh entendi, faz sentido, tinha esquecido desse adicional. Tudo certo então", hoursAgo: 24 },
      { direction: "OUTBOUND", text: "Que bom! Qualquer dúvida em fatura é só chamar por aqui mesmo", hoursAgo: 6 },
    ],
  },
  {
    client: "Construtora Horizonte",
    phoneSuffix: "999990007",
    messages: [
      { direction: "INBOUND", text: "Fala, e aí, o vídeo institucional do novo empreendimento fica pronto quando?", hoursAgo: 55 },
      { direction: "OUTBOUND", text: "Oi Eduardo! Está em edição final, previsão de entrega é quinta-feira", hoursAgo: 53 },
      { direction: "INBOUND", text: "Quinta serve, vamos usar no evento de lançamento no sábado", hoursAgo: 52 },
      { direction: "OUTBOUND", text: "Perfeito, vamos garantir que chegue com folga então, te aviso assim que renderizar", hoursAgo: 51 },
      { direction: "INBOUND", text: "E aí, saiu?", hoursAgo: 11 },
      { direction: "OUTBOUND", text: "Saiu sim! Te mandei por e-mail e também aqui, dá uma olhada", hoursAgo: 9 },
      { direction: "INBOUND", text: "Ficou excelente, muito obrigado pela pontualidade", hoursAgo: 7 },
    ],
  },
  {
    client: "Clínica Bem Estar",
    phoneSuffix: "999990008",
    messages: [
      { direction: "INBOUND", text: "Oi, gente! Só passando pra contar que esse mês bateu recorde de agendamentos pelo Instagram", hoursAgo: 44 },
      { direction: "OUTBOUND", text: "Que notícia maravilhosa, Dra. Fernanda! Isso reflete bem o trabalho de conteúdo que vocês vêm topando fazer", hoursAgo: 42 },
      { direction: "INBOUND", text: "Com certeza, o pessoal adorou os vídeos de bastidor da clínica", hoursAgo: 41 },
      { direction: "OUTBOUND", text: "Vamos manter esse ritmo então, já tenho ideias novas pro próximo mês", hoursAgo: 40 },
      { direction: "INBOUND", text: "Adorei saber disso, seguimos juntos!", hoursAgo: 5 },
    ],
  },
  {
    client: "Advocacia Martins & Souza",
    phoneSuffix: "999990009",
    messages: [
      { direction: "INBOUND", text: "Boa tarde, surgiu uma pauta urgente: saiu uma mudança na lei que afeta bastante nossos clientes, dá pra fazer um post ainda hoje?", hoursAgo: 15 },
      { direction: "OUTBOUND", text: "Boa tarde Dr. André! Dá sim, me manda os pontos principais que já monto o texto", hoursAgo: 14 },
      { direction: "INBOUND", text: "Te mando em áudio em 10 minutos", hoursAgo: 13 },
      { direction: "OUTBOUND", text: "Combinado, fico no aguardo", hoursAgo: 12 },
      { direction: "INBOUND", text: "Áudio enviado, é sobre a nova regra de reajuste de aluguel", hoursAgo: 11 },
      { direction: "OUTBOUND", text: "Recebido! Em 1h te mando o rascunho pra aprovação", hoursAgo: 9 },
      { direction: "INBOUND", text: "Aprovado, pode publicar agora", hoursAgo: 4 },
      { direction: "OUTBOUND", text: "Publicado! Já está no ar", hoursAgo: 2 },
    ],
  },
  {
    client: "Escola Fluent Idiomas",
    phoneSuffix: "999990010",
    messages: [
      { direction: "INBOUND", text: "Oi, não estou conseguindo acessar o grupo de aprovação de posts, dá erro de permissão", hoursAgo: 34 },
      { direction: "OUTBOUND", text: "Oi Beatriz! Estranho, deixa eu verificar aqui as permissões do seu usuário", hoursAgo: 33 },
      { direction: "INBOUND", text: "Beleza, obrigada", hoursAgo: 32 },
      { direction: "OUTBOUND", text: "Encontrei o problema, seu acesso tinha expirado no sistema. Já reativei, tenta de novo?", hoursAgo: 30 },
      { direction: "INBOUND", text: "Consegui entrar agora, funcionou! Obrigada pela agilidade", hoursAgo: 29 },
      { direction: "OUTBOUND", text: "Que bom! Qualquer outro problema de acesso é só chamar por aqui", hoursAgo: 3 },
    ],
  },
  {
    client: "Bella Moda Boutique",
    phoneSuffix: "999990011",
    messages: [
      { direction: "INBOUND", text: "Oi, queria dar um feedback: a Camila do time de vocês tem sido super atenciosa, sempre responde rápido", hoursAgo: 46 },
      { direction: "OUTBOUND", text: "Que alegria receber isso, Mariana! Vou repassar pra ela, com certeza vai adorar saber", hoursAgo: 44 },
      { direction: "INBOUND", text: "Faz toda diferença ter alguém tão solícito cuidando da marca", hoursAgo: 43 },
      { direction: "OUTBOUND", text: "Ficamos muito felizes mesmo, obrigada por compartilhar isso com a gente", hoursAgo: 42 },
      { direction: "INBOUND", text: "Só reforçando, continuem assim! 👏", hoursAgo: 6 },
    ],
  },
  {
    client: "Clínica Vitalis",
    phoneSuffix: "999990012",
    messages: [
      { direction: "INBOUND", text: "Bom dia! Vi a proposta de campanha pro Setembro Amarelo, gostei da ideia mas queria suavizar um pouco o tom, tá muito pesado", hoursAgo: 62 },
      { direction: "OUTBOUND", text: "Bom dia Dra. Camila! Faz sentido, vamos equilibrar mais entre acolhimento e informação. Ajusto e te mando novo roteiro", hoursAgo: 60 },
      { direction: "INBOUND", text: "Perfeito, fico no aguardo", hoursAgo: 59 },
      { direction: "OUTBOUND", text: "Dra. Camila, roteiro novo pronto, ficou bem mais leve mantendo a mensagem importante", hoursAgo: 24 },
      { direction: "INBOUND", text: "Gostei muito, aprovado! Pode produzir", hoursAgo: 22 },
      { direction: "OUTBOUND", text: "Show, já colocamos em produção, entrega prevista até dia 20", hoursAgo: 20 },
    ],
  },
  {
    client: "AgroForte Insumos",
    phoneSuffix: "999990013",
    messages: [
      { direction: "INBOUND", text: "Fala! Os anúncios de captação de revendedores estão gerando poucos leads esse mês, o que houve?", hoursAgo: 70 },
      { direction: "OUTBOUND", text: "Oi João Pedro! Notamos isso também, o público já está meio saturado. Vamos testar uma nova segmentação por região", hoursAgo: 68 },
      { direction: "INBOUND", text: "Beleza, quando começa o teste?", hoursAgo: 67 },
      { direction: "OUTBOUND", text: "Já configurei, deve começar a rodar amanhã de manhã", hoursAgo: 66 },
      { direction: "INBOUND", text: "E aí, como estão os números do teste?", hoursAgo: 17 },
      { direction: "OUTBOUND", text: "Melhorou bastante! Custo por lead caiu quase 30%, vou te mandar o relatório completo", hoursAgo: 15 },
      { direction: "INBOUND", text: "Excelente notícia, manda sim", hoursAgo: 9 },
    ],
  },
  {
    client: "Studio Pilates Corpo Leve",
    phoneSuffix: "999990014",
    messages: [
      { direction: "INBOUND", text: "Oi! Queria bater um papo rápido sobre a campanha de matrículas de setembro, tem um horário essa semana?", hoursAgo: 26 },
      { direction: "OUTBOUND", text: "Oi Renata! Tenho amanhã às 14h ou quinta de manhã, qual prefere?", hoursAgo: 25 },
      { direction: "INBOUND", text: "Amanhã 14h fecha comigo", hoursAgo: 24 },
      { direction: "OUTBOUND", text: "Combinado, te mando o link da chamada", hoursAgo: 23 },
      { direction: "INBOUND", text: "Foi ótima nossa conversa, já anotei tudo o que vamos fazer", hoursAgo: 4 },
      { direction: "OUTBOUND", text: "Também gostei muito! Já começo a preparar os primeiros criativos", hoursAgo: 2 },
    ],
  },
  {
    client: "Auto Center Veloz",
    phoneSuffix: "999990015",
    messages: [
      { direction: "INBOUND", text: "Chegaram as fotos do estúdio, ficaram show demais, parabéns!", hoursAgo: 38 },
      { direction: "OUTBOUND", text: "Que bom que gostou, Ricardo! O fotógrafo capturou bem o brilho dos carros", hoursAgo: 36 },
      { direction: "INBOUND", text: "De fato. Só uma coisa, dá pra cortar o reflexo do teto na foto do SUV prata?", hoursAgo: 35 },
      { direction: "OUTBOUND", text: "Dá sim, já mando pro editor e te devolvo até amanhã", hoursAgo: 34 },
      { direction: "INBOUND", text: "Ficou perfeita agora, obrigado!", hoursAgo: 10 },
      { direction: "OUTBOUND", text: "Disponha! Já subo pro banco de imagens dos anúncios", hoursAgo: 8 },
    ],
  },
  {
    client: "Hotel Mirante da Serra",
    phoneSuffix: "999990016",
    messages: [
      { direction: "INBOUND", text: "Oi! Precisamos que a campanha de férias de julho esteja no ar até dia 15 no mais tardar, dá tempo?", hoursAgo: 80 },
      { direction: "OUTBOUND", text: "Oi Sofia! Dá sim, já estamos produzindo as artes e vídeos, previsão de entrega é dia 10", hoursAgo: 78 },
      { direction: "INBOUND", text: "Ótimo, isso nos dá uma folga boa pra revisar", hoursAgo: 77 },
      { direction: "OUTBOUND", text: "Sofia, adiantando: o material vai ficar pronto amanhã, um dia antes do combinado", hoursAgo: 32 },
      { direction: "INBOUND", text: "Que notícia boa, muito obrigada pela antecedência", hoursAgo: 30 },
      { direction: "OUTBOUND", text: "Acabou de sair, te mandei tudo por e-mail pra aprovação", hoursAgo: 13 },
      { direction: "INBOUND", text: "Recebido, vou olhar com a equipe e te retorno até amanhã", hoursAgo: 11 },
    ],
  },
  {
    client: "Padaria Pão Nosso",
    phoneSuffix: "999990017",
    messages: [
      { direction: "INBOUND", text: "Boa tarde! Vamos fazer uma promoção relâmpago amanhã de pão de queijo, dá pra fazer um post ainda hoje à noite?", hoursAgo: 20 },
      { direction: "OUTBOUND", text: "Boa tarde Seu Antônio! Dá sim, me passa o preço e o horário da promoção que já monto", hoursAgo: 19 },
      { direction: "INBOUND", text: "R$ 12,90 a dúzia, das 7h às 10h só amanhã", hoursAgo: 18 },
      { direction: "OUTBOUND", text: "Perfeito, te mando a arte em 30 minutos", hoursAgo: 16 },
      { direction: "INBOUND", text: "Ficou ótima! Pode publicar já", hoursAgo: 15 },
      { direction: "OUTBOUND", text: "Publicado agora, também coloquei no Stories com contagem regressiva", hoursAgo: 14 },
      { direction: "INBOUND", text: "Deu um movimento muito bom hoje de manhã, obrigado pela força!", hoursAgo: 1 },
    ],
  },
  {
    client: "Distribuidora Bebidas Já",
    phoneSuffix: "999990018",
    messages: [
      { direction: "INBOUND", text: "Fala, tudo bem? Ainda não caiu aqui o boleto desse mês, já venceu?", hoursAgo: 42 },
      { direction: "OUTBOUND", text: "Oi Paulo! Deixa eu verificar, um segundo", hoursAgo: 40 },
      { direction: "INBOUND", text: "Beleza", hoursAgo: 39 },
      { direction: "OUTBOUND", text: "Encontrei o problema, o e-mail tinha ido pra caixa de spam. Vou reenviar agora mesmo", hoursAgo: 37 },
      { direction: "INBOUND", text: "Recebi aqui, obrigado! Já vou efetuar o pagamento", hoursAgo: 36 },
      { direction: "OUTBOUND", text: "Pagamento confirmado aqui do nosso lado, obrigada Paulo!", hoursAgo: 5 },
    ],
  },
];

export const ACTIVITY_LOG_ENTRIES: { action: string; entityType: string; summary: string; daysAgo: number }[] = [
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Loja Aurora\" criado", daysAgo: 0 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Pele Bonita Cosméticos\" criado", daysAgo: 1 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Gestão de Tráfego Pago - TechFlow Soluções\" criado", daysAgo: 2 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Vida Fitness Academia\" criado", daysAgo: 2 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Produção de Conteúdo - Doce Encanto Confeitaria\" criado", daysAgo: 3 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Construtora Horizonte\" criado", daysAgo: 3 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Serviços Extras - Sabor Caseiro Restaurante\" criado", daysAgo: 4 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Clínica Bem Estar\" criado", daysAgo: 4 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Aluguel do escritório\" criado", daysAgo: 5 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Assinatura de ferramentas\" criado", daysAgo: 6 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Advocacia Martins & Souza\" criado", daysAgo: 6 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Freelancer - Design\" criado", daysAgo: 7 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Escola Fluent Idiomas\" criado", daysAgo: 8 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Investimento em Mídia - AgroForte Insumos\" criado", daysAgo: 9 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Hotel Mirante da Serra\" criado", daysAgo: 10 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Salário - equipe\" criado", daysAgo: 15 },
  { action: "create", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Padaria Pão Nosso\" criado", daysAgo: 18 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - TechFlow Soluções\" editado", daysAgo: 2 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Produção de Conteúdo - Bella Moda Boutique\" editado", daysAgo: 3 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Clínica Vitalis\" editado", daysAgo: 4 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Investimento em Mídia - Auto Center Veloz\" editado", daysAgo: 5 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Distribuidora Bebidas Já\" editado", daysAgo: 7 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Serviços Extras - Studio Pilates Corpo Leve\" editado", daysAgo: 8 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Ótica Visão Clara\" editado", daysAgo: 9 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Assinatura de ferramentas\" editado", daysAgo: 11 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - Sabor da Serra Restaurante\" editado", daysAgo: 12 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Freelancer - Vídeo\" editado", daysAgo: 14 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Mensalidade - AgroForte Insumos\" editado", daysAgo: 20 },
  { action: "update", entityType: "Transaction", summary: "Lançamento financeiro \"Aluguel do escritório\" editado", daysAgo: 25 },
  { action: "delete", entityType: "Transaction", summary: "Lançamento financeiro \"Serviços Extras - Pet Feliz\" excluído", daysAgo: 30 },
  { action: "delete", entityType: "Transaction", summary: "Lançamento financeiro \"Freelancer - Design\" excluído", daysAgo: 40 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - Vida Fitness Academia\"", daysAgo: 0 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - Loja Aurora\"", daysAgo: 1 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - Sabor Caseiro Restaurante\"", daysAgo: 5 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - Clínica Bem Estar\"", daysAgo: 6 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - TechFlow Soluções\"", daysAgo: 10 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - Construtora Horizonte\"", daysAgo: 15 },
  { action: "charge", entityType: "Transaction", summary: "Cobrança gerada pra \"Mensalidade - Hotel Mirante da Serra\"", daysAgo: 22 },
  { action: "create", entityType: "Client", summary: "Cliente \"Sabor da Serra Restaurante\" criado", daysAgo: 35 },
  { action: "create", entityType: "Client", summary: "Cliente \"Clínica Vitalis\" criado", daysAgo: 33 },
  { action: "create", entityType: "Client", summary: "Cliente \"Ótica Visão Clara\" criado", daysAgo: 30 },
  { action: "create", entityType: "Client", summary: "Cliente \"Bella Moda Boutique\" criado", daysAgo: 28 },
  { action: "create", entityType: "Client", summary: "Cliente \"Studio Pilates Corpo Leve\" criado", daysAgo: 20 },
  { action: "create", entityType: "Client", summary: "Cliente \"Distribuidora Bebidas Já\" criado", daysAgo: 12 },
  { action: "create", entityType: "Client", summary: "Cliente \"Doce Encanto Confeitaria\" criado", daysAgo: 6 },
  { action: "update", entityType: "Client", summary: "Cliente \"Loja Aurora\" editado", daysAgo: 2 },
  { action: "update", entityType: "Client", summary: "Cliente \"Pele Bonita Cosméticos\" editado", daysAgo: 3 },
  { action: "update", entityType: "Client", summary: "Cliente \"TechFlow Soluções\" editado", daysAgo: 4 },
  { action: "update", entityType: "Client", summary: "Cliente \"Construtora Horizonte\" editado", daysAgo: 5 },
  { action: "update", entityType: "Client", summary: "Cliente \"Clínica Bem Estar\" editado", daysAgo: 6 },
  { action: "update", entityType: "Client", summary: "Cliente \"Advocacia Martins & Souza\" editado", daysAgo: 8 },
  { action: "update", entityType: "Client", summary: "Cliente \"Escola Fluent Idiomas\" editado", daysAgo: 9 },
  { action: "update", entityType: "Client", summary: "Cliente \"AgroForte Insumos\" editado", daysAgo: 11 },
  { action: "update", entityType: "Client", summary: "Cliente \"Auto Center Veloz\" editado", daysAgo: 14 },
  { action: "update", entityType: "Client", summary: "Cliente \"Padaria Pão Nosso\" editado", daysAgo: 17 },
  { action: "update", entityType: "Client", summary: "Cliente \"Vida Fitness Academia\" editado", daysAgo: 24 },
  { action: "delete", entityType: "Client", summary: "Cliente \"Móveis Elegance\" excluído", daysAgo: 42 },
  { action: "delete", entityType: "Client", summary: "Cliente \"Pet Feliz\" excluído", daysAgo: 38 },
  { action: "create", entityType: "ContractedService", summary: "Serviço contratado \"Gestão de Redes Sociais\" adicionado", daysAgo: 3 },
  { action: "create", entityType: "ContractedService", summary: "Serviço contratado \"Gestão de Tráfego Pago\" adicionado", daysAgo: 5 },
  { action: "create", entityType: "ContractedService", summary: "Serviço contratado \"Produção de Vídeo\" adicionado", daysAgo: 9 },
  { action: "create", entityType: "ContractedService", summary: "Serviço contratado \"SEO\" adicionado", daysAgo: 13 },
  { action: "create", entityType: "ContractedService", summary: "Serviço contratado \"Email Marketing\" adicionado", daysAgo: 19 },
  { action: "create", entityType: "ContractedService", summary: "Serviço contratado \"Fotografia de Produto\" adicionado", daysAgo: 27 },
  { action: "update", entityType: "ContractedService", summary: "Serviço contratado \"Gestão de Redes Sociais\" editado", daysAgo: 7 },
  { action: "update", entityType: "ContractedService", summary: "Serviço contratado \"Copywriting\" editado", daysAgo: 16 },
  { action: "update", entityType: "ContractedService", summary: "Serviço contratado \"Assessoria de Imprensa\" editado", daysAgo: 23 },
  { action: "delete", entityType: "ContractedService", summary: "Serviço contratado \"Fotografia de Produto\" removido", daysAgo: 34 },
  { action: "create", entityType: "SalesProposal", summary: "Proposta \"Proposta - Studio Vetor Arquitetura\" criada", daysAgo: 15 },
  { action: "create", entityType: "SalesProposal", summary: "Proposta \"Proposta - Café Raiz\" criada", daysAgo: 10 },
  { action: "create", entityType: "SalesProposal", summary: "Proposta \"Proposta - Nutri Ana Paula Consultório\" criada", daysAgo: 6 },
  { action: "sign", entityType: "SalesProposal", summary: "Contrato da proposta \"Proposta - Café Raiz\" assinado por Bruno Alencar", daysAgo: 8 },
  { action: "sign", entityType: "SalesProposal", summary: "Contrato da proposta \"Proposta - Studio Vetor Arquitetura\" assinado por Renata Vaz", daysAgo: 13 },
  { action: "sign", entityType: "SalesProposal", summary: "Contrato da proposta \"Proposta - TechFlow Soluções\" assinado por Diego Almeida", daysAgo: 25 },
  { action: "sign", entityType: "SalesProposal", summary: "Contrato da proposta \"Proposta - Hotel Mirante da Serra\" assinado por Sofia Albuquerque", daysAgo: 32 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - Studio Vetor Arquitetura\" aceita por Renata Vaz", daysAgo: 14 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - Café Raiz\" aceita por Bruno Alencar", daysAgo: 9 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - Nutri Ana Paula Consultório\" aceita por Ana Paula Ribeiro", daysAgo: 5 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - AgroForte Insumos\" aceita por João Pedro Sales", daysAgo: 21 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - Distribuidora Bebidas Já\" aceita por Paulo Vitor", daysAgo: 11 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - Auto Center Veloz\" aceita por Ricardo Prado", daysAgo: 28 },
  { action: "proposal_accepted", entityType: "SalesProposal", summary: "Proposta \"Proposta - Escola Fluent Idiomas\" aceita por Beatriz Souza", daysAgo: 4 },
  { action: "proposal_rejected", entityType: "SalesProposal", summary: "Proposta \"Proposta - Móveis Elegance\" recusada por Simone Castro", daysAgo: 36 },
  { action: "proposal_rejected", entityType: "SalesProposal", summary: "Proposta \"Proposta - Contabilidade Rumo Certo\" recusada por Marcelo Tavares", daysAgo: 45 },
  { action: "proposal_changes_requested", entityType: "SalesProposal", summary: "Proposta \"Proposta - Pele Bonita Cosméticos\" com alterações solicitadas por Rodrigo Nunes", daysAgo: 7 },
  { action: "proposal_changes_requested", entityType: "SalesProposal", summary: "Proposta \"Proposta - Nutri Ana Paula Consultório\" com alterações solicitadas por Ana Paula Ribeiro", daysAgo: 8 },
  { action: "create", entityType: "User", summary: "Usuário \"Isabela Santos\" criado (Membro)", daysAgo: 40 },
  { action: "create", entityType: "User", summary: "Usuário \"Rafael Tavares\" criado (Membro)", daysAgo: 25 },
  { action: "create", entityType: "User", summary: "Usuário \"Juliana Prado\" criado (Admin)", daysAgo: 10 },
  { action: "update", entityType: "User", summary: "Usuário \"Rafael Tavares\" editado", daysAgo: 5 },
];
